# Generated by Django 5.1.3 on 2024-11-16 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='notes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserNotes', to='myApp.usernotes'),
        ),
    ]
