# Generated by Django 5.1.3 on 2024-11-16 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_customuser_notes_alter_usernotes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='notes',
        ),
        migrations.AlterField(
            model_name='usernotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomUser', to='myApp.customuser'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notes',
            field=models.ManyToManyField(blank=True, null=True, related_name='UserNotes', to='myApp.usernotes'),
        ),
    ]
