# Generated by Django 5.1.3 on 2024-11-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_remove_customuser_notes_alter_usernotes_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='UserNotes', to='myApp.usernotes'),
        ),
    ]
