# Generated by Django 5.1.3 on 2024-11-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_customuser_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='notes',
        ),
    ]
