# Generated by Django 5.1.3 on 2024-11-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_remove_customuser_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='UserNotes', to='myApp.usernotes'),
        ),
    ]
