# Generated by Django 5.1.3 on 2024-11-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_remove_customuser_username_customuser_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='notes',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='username', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
