# Generated by Django 5.1.3 on 2024-11-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='about',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
