# Generated by Django 5.1.3 on 2024-11-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='media/profile_pics/default.jpg', upload_to='media/profile_pics/'),
        ),
    ]
